services:
  - type: web
    name: odoo-excel-uploader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    healthCheckPath: /
